[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.32.13"

[[constraint]]
  name = "github.com/cheynewallace/tabby"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
